### ISSUE TITLE
icons not showing in my ubuntu 20.04 ulauncher 5.7.5

### ISSUE THREAD

**Issue by A-Nivethan** [dflock/ulauncher-window-switcher#8]
![issue2](https://user-images.githubusercontent.com/63112138/126891608-4e136bc8-6730-4f8c-8838-e6f1f51e7f97.jpeg)

**Comment by dflock** [comment]
What you're seeing is correct - those are the correct icons - it doesn't attempt to fetch icons for each application in the list. Doing so would be considerably more complex and slower, so it just shows a generic "Window" icon for each window.

**Comment by A-Nivethan** [comment]
I just figure it out after checking the code and thanks for the reply.
